import { randomBytes } from "node:crypto";
import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  renameSync,
  rmSync,
  unlinkSync,
  writeFileSync,
} from "node:fs";
import path from "node:path";

const ROLE_PATTERN = /^[a-z][a-z0-9-]*$/;
const CONTROL_PATTERN = /[\u0000-\u001f\u007f-\u009f]/;
export const PROMPT_INTENT_MARKER = "<!-- gsb:intent -->";

export function composeRolePrompt(role) {
  const custom = role?.promptMode === "custom";
  const layered = !custom && (typeof role?.promptBase === "string" || typeof role?.intent === "string");
  if (role?.id === "hub" || !layered) return typeof role?.prompt === "string" ? role.prompt.trim() : "";
  const base = (role.promptBase || "").trim();
  const intent = (role.intent || "").trim();
  return `${base}\n\n${PROMPT_INTENT_MARKER}${intent ? `\n\n${intent}` : ""}`;
}

function readText(file, fallback = "") {
  try {
    return readFileSync(file, "utf8");
  } catch {
    return fallback;
  }
}

export function parseRoleMap(content) {
  const rows = [];
  for (const rawLine of content.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) continue;
    const separator = line.indexOf("=");
    if (separator < 1) throw new Error(`Invalid role mapping: ${rawLine}`);
    rows.push({ id: line.slice(0, separator).trim().replaceAll("_", "-"), value: line.slice(separator + 1).trim() });
  }
  return rows;
}

export function serializeAgents(workbench) {
  const roles = Array.isArray(workbench?.roles) ? workbench.roles : [];
  return ["# Generated by GSB Studio. Edit in Studio or keep role=agent syntax.", "", ...roles.map((role) => `${role.id}=${role.agent}`), ""].join("\n");
}

export function serializeModels(workbench) {
  const roles = Array.isArray(workbench?.roles) ? workbench.roles : [];
  const rows = roles.filter((role) => typeof role.model === "string" && role.model.trim()).map((role) => `${role.id}=${role.model.trim()}`);
  return rows.length ? ["# Optional per-role model overrides generated by GSB Studio.", "", ...rows, ""].join("\n") : "";
}

function sidecarValue(workbench) {
  return {
    version: workbench.version || 1,
    name: workbench.name,
    profile: workbench.profile,
    session: workbench.session,
    permission: workbench.permission,
    watchdog: workbench.watchdog,
    rebuild: workbench.rebuild,
    roles: (workbench.roles || []).map((role) => ({
      id: role.id,
      name: role.name,
      type: role.type,
      description: role.description,
    })),
  };
}

export function serializeWorkbenchSidecar(workbench) {
  return `${JSON.stringify(sidecarValue(workbench), null, 2)}\n`;
}

function assertStagedRoundTrip(workbench, stagingDirectory) {
  for (const role of workbench.roles) {
    if (!ROLE_PATTERN.test(role.id || "")) throw new Error(`角色 ID 无法写入：${role.id || "<empty>"}`);
    if (CONTROL_PATTERN.test(role.agent || "") || /^(claude|codex|kimi|shell):\s*$/.test(role.agent || "")) {
      throw new Error(`角色 ${role.id} 的 Agent 无法安全写入`);
    }
    if (CONTROL_PATTERN.test(role.model || "")) throw new Error(`角色 ${role.id} 的模型无法安全写入`);
  }
  const agentRows = parseRoleMap(readText(path.join(stagingDirectory, "agents.conf")));
  if (agentRows.some((row) => !row.value)) throw new Error("agents.conf 的 Agent 值不能为空");
  if (new Set(agentRows.map((row) => row.id)).size !== agentRows.length) throw new Error("agents.conf 包含重复角色 ID");
  if (agentRows.length !== workbench.roles.length || agentRows.some((row, index) => (
    row.id !== workbench.roles[index].id || row.value !== workbench.roles[index].agent.trim()
  ))) throw new Error("agents.conf round-trip 自检失败");
  if (!agentRows.some((row) => row.id === "hub")) throw new Error("agents.conf 缺少 hub");

  const modelsFile = path.join(stagingDirectory, "models.conf");
  const modelRows = existsSync(modelsFile) ? parseRoleMap(readText(modelsFile)) : [];
  const expectedModels = workbench.roles.filter((role) => typeof role.model === "string" && role.model.trim());
  if (modelRows.length !== expectedModels.length || modelRows.some((row, index) => (
    row.id !== expectedModels[index].id || row.value !== expectedModels[index].model.trim()
  ))) throw new Error("models.conf round-trip 自检失败");

  for (const role of workbench.roles) {
    const promptName = role.id === "hub" ? "hub-extension.md" : `${role.id}.md`;
    if (!existsSync(path.join(stagingDirectory, "prompts", promptName))) throw new Error(`缺少 prompt：${promptName}`);
    if (role.id !== "hub" && !readText(path.join(stagingDirectory, "prompts", promptName)).trim()) {
      throw new Error(`角色 ${role.id} 的 prompt 不能为空`);
    }
  }
  const sidecar = JSON.parse(readText(path.join(stagingDirectory, "workbench.json")));
  if ((sidecar.roles || []).some((role) => "agent" in role || "model" in role || "prompt" in role)) {
    throw new Error("workbench.json 包含权威配置字段");
  }
}

function readRawSidecar(workspace) {
  try {
    const value = JSON.parse(readText(path.join(workspace, ".gsb-local", "workbench.json")));
    return value && typeof value === "object" ? value : null;
  } catch {
    return null;
  }
}

function sidecarFields(workspace, value) {
  if (!value) return null;
  const saved = { workspace };
  for (const key of ["version", "name", "profile", "session", "permission", "watchdog", "rebuild"]) {
    if (value[key] !== undefined) saved[key] = value[key];
  }
  saved.roles = Array.isArray(value.roles) ? value.roles.flatMap((role) => (
    role && typeof role === "object" && typeof role.id === "string"
      ? [{ id: role.id, name: role.name, type: role.type, description: role.description }]
      : []
  )) : [];
  return saved;
}

function readModelMap(workspace) {
  const file = path.join(workspace, ".gsb-local", "models.conf");
  if (!existsSync(file)) return new Map();
  return new Map(parseRoleMap(readText(file)).map(({ id, value }) => [id, value]));
}

export function saveProjectState(workbench) {
  const localDirectory = path.join(workbench.workspace, ".gsb-local");
  mkdirSync(localDirectory, { recursive: true });
  const stagingDirectory = path.join(localDirectory, `.staging-${process.pid}-${randomBytes(4).toString("hex")}`);
  const stagingPrompts = path.join(stagingDirectory, "prompts");
  mkdirSync(stagingPrompts, { recursive: true });
  writeFileSync(path.join(stagingDirectory, "agents.conf"), serializeAgents(workbench), { mode: 0o600 });
  const models = serializeModels(workbench);
  if (models) writeFileSync(path.join(stagingDirectory, "models.conf"), models, { mode: 0o600 });
  for (const role of workbench.roles) {
    const promptName = role.id === "hub" ? "hub-extension.md" : `${role.id}.md`;
    writeFileSync(path.join(stagingPrompts, promptName), `${composeRolePrompt(role).trim()}\n`, { mode: 0o600 });
  }
  writeFileSync(path.join(stagingDirectory, "workbench.json"), serializeWorkbenchSidecar(workbench), { mode: 0o600 });

  try {
    assertStagedRoundTrip(workbench, stagingDirectory);
  } catch (error) {
    rmSync(stagingDirectory, { recursive: true, force: true });
    throw new Error(`配置预校验失败：${error.message}`);
  }

  const promptDirectory = path.join(localDirectory, "prompts");
  mkdirSync(promptDirectory, { recursive: true });
  try {
    renameSync(path.join(stagingDirectory, "agents.conf"), path.join(localDirectory, "agents.conf"));
    const stagedModels = path.join(stagingDirectory, "models.conf");
    const modelsFile = path.join(localDirectory, "models.conf");
    if (existsSync(stagedModels)) renameSync(stagedModels, modelsFile);
    else if (existsSync(modelsFile)) unlinkSync(modelsFile);
    for (const role of workbench.roles) {
      const promptName = role.id === "hub" ? "hub-extension.md" : `${role.id}.md`;
      renameSync(path.join(stagingPrompts, promptName), path.join(promptDirectory, promptName));
    }
    const currentPromptFiles = new Set(workbench.roles.map((role) => role.id === "hub" ? "hub-extension.md" : `${role.id}.md`));
    for (const entry of readdirSync(promptDirectory, { withFileTypes: true })) {
      const role = entry.name.endsWith(".md") ? entry.name.slice(0, -3) : "";
      if (entry.isFile() && ROLE_PATTERN.test(role) && !currentPromptFiles.has(entry.name)) {
        unlinkSync(path.join(promptDirectory, entry.name));
      }
    }
    // The UI sidecar is the commit marker and is intentionally renamed last.
    renameSync(path.join(stagingDirectory, "workbench.json"), path.join(localDirectory, "workbench.json"));
    rmSync(stagingDirectory, { recursive: true, force: true });
  } catch (error) {
    error.message = `配置提交失败；staging 副本保留在 ${stagingDirectory}：${error.message}`;
    error.stagingDirectory = stagingDirectory;
    throw error;
  }
}

export function loadProjectState(workspace, options) {
  const {
    profiles,
    prompts,
    roleMeta,
    defaultWorkbench,
    promptForRole,
    normalizeWorkbench,
    validateWorkbench,
  } = options;
  let rawSidecar = readRawSidecar(workspace);
  const agentsFile = path.join(workspace, ".gsb-local", "agents.conf");
  if (!existsSync(agentsFile) && Array.isArray(rawSidecar?.roles) && rawSidecar.roles.length) {
    const legacy = normalizeWorkbench({ ...rawSidecar, workspace });
    if (validateWorkbench(legacy).valid) {
      saveProjectState(legacy);
      rawSidecar = readRawSidecar(workspace);
    }
  }

  const saved = sidecarFields(workspace, rawSidecar);
  const selectedProfile = profiles.find((profile) => profile.id === saved?.profile)
    || profiles.find((profile) => profile.id === "config1")
    || profiles[0];
  const fallback = defaultWorkbench(workspace, selectedProfile, prompts);
  if (!existsSync(agentsFile)) {
    const { roles: _savedRoles, ...savedFields } = saved || {};
    return normalizeWorkbench({ ...fallback, ...savedFields, workspace });
  }

  const models = readModelMap(workspace);
  const savedRoles = new Map((saved?.roles || []).map((role) => [role.id, role]));
  const roles = parseRoleMap(readText(agentsFile)).map(({ id, value: agent }) => {
    const known = roleMeta[id];
    const metadata = savedRoles.get(id) || {};
    const prompt = promptForRole(workspace, id, prompts);
    return {
      id,
      name: known?.name || metadata.name || id,
      type: known?.type || metadata.type || "specialist",
      description: known?.description || metadata.description || "自定义协作角色",
      agent,
      model: models.get(id) || "",
      promptTemplate: prompt.template,
      prompt: prompt.body,
      promptBase: prompt.promptBase,
      intent: prompt.intent,
      promptMode: prompt.promptMode,
    };
  });
  const { roles: _savedRoles, ...savedFields } = saved || {};
  return normalizeWorkbench({ ...fallback, ...savedFields, workspace, roles });
}
