import { randomBytes } from "node:crypto";
import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  renameSync,
  rmSync,
  unlinkSync,
  writeFileSync,
} from "node:fs";
import path from "node:path";

const ROLE_PATTERN = /^[a-z][a-z0-9-]*$/;
const PROJECT_PATTERN = /^[A-Za-z0-9][A-Za-z0-9._-]*$/;
const CONTROL_PATTERN = /[\u0000-\u001f\u007f-\u009f]/;
const PROJECT_FILES = ["agents.conf", "models.conf", "prompts", "workbench.json"];
export const PROMPT_INTENT_MARKER = "<!-- gsb:intent -->";

function localRoot(workspace) {
  return path.join(workspace, ".gsb-local");
}

export function projectDir(workspace, name) {
  if (!PROJECT_PATTERN.test(name || "")) throw new Error("项目名只能包含字母、数字、点、下划线和连字符");
  return path.join(localRoot(workspace), "projects", name);
}

function rawSidecar(directory) {
  try {
    const value = JSON.parse(readText(path.join(directory, "workbench.json")));
    return value && typeof value === "object" ? value : null;
  } catch {
    return null;
  }
}

function legacyProjectName(workspace, sidecar = rawSidecar(localRoot(workspace))) {
  const candidates = [sidecar?.projectName, sidecar?.name, sidecar?.session, path.basename(workspace)];
  return candidates.find((name) => PROJECT_PATTERN.test(name || "")) || "seed-gsb";
}

// Cheap sidecar-only read for listings: avoids a full loadProjectState per row.
export function storedTemplateId(directory) {
  const origin = normalizedTemplateOrigin(rawSidecar(directory));
  return origin?.id || "";
}

export function listStoredProjects(workspace) {
  const projectsRoot = path.join(localRoot(workspace), "projects");
  const named = existsSync(projectsRoot) ? readdirSync(projectsRoot, { withFileTypes: true })
    .filter((entry) => entry.isDirectory() && PROJECT_PATTERN.test(entry.name) && !entry.name.startsWith(".staging-"))
    .filter((entry) => PROJECT_FILES.some((name) => existsSync(path.join(projectsRoot, entry.name, name))))
    .map((entry) => ({ path: workspace, name: entry.name, directory: path.join(projectsRoot, entry.name), legacy: false }))
    .sort((left, right) => left.name.localeCompare(right.name)) : [];
  const directory = localRoot(workspace);
  if (!PROJECT_FILES.some((name) => existsSync(path.join(directory, name)))) return named;
  const legacy = { path: workspace, name: legacyProjectName(workspace), directory, legacy: true };
  return named.some((project) => project.name === legacy.name) ? named : [...named, legacy]
    .sort((left, right) => left.name.localeCompare(right.name));
}

export function composeRolePrompt(role) {
  const custom = role?.promptMode === "custom";
  const layered = !custom && (typeof role?.promptBase === "string" || typeof role?.intent === "string");
  if (role?.id === "hub" || !layered) return typeof role?.prompt === "string" ? role.prompt.trim() : "";
  const base = (role.promptBase || "").trim();
  const intent = (role.intent || "").trim();
  return `${base}\n\n${PROMPT_INTENT_MARKER}${intent ? `\n\n${intent}` : ""}`;
}

function readText(file, fallback = "") {
  try {
    return readFileSync(file, "utf8");
  } catch {
    return fallback;
  }
}

export function parseRoleMap(content) {
  const rows = [];
  for (const rawLine of content.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) continue;
    const separator = line.indexOf("=");
    if (separator < 1) throw new Error(`Invalid role mapping: ${rawLine}`);
    rows.push({ id: line.slice(0, separator).trim().replaceAll("_", "-"), value: line.slice(separator + 1).trim() });
  }
  return rows;
}

export function serializeAgents(workbench) {
  const roles = Array.isArray(workbench?.roles) ? workbench.roles : [];
  return ["# Generated by GSB Studio. Edit in Studio or keep role=agent syntax.", "", ...roles.map((role) => `${role.id}=${role.agent}`), ""].join("\n");
}

export function serializeModels(workbench) {
  const roles = Array.isArray(workbench?.roles) ? workbench.roles : [];
  const rows = roles.filter((role) => typeof role.model === "string" && role.model.trim()).map((role) => `${role.id}=${role.model.trim()}`);
  return rows.length ? ["# Optional per-role model overrides generated by GSB Studio.", "", ...rows, ""].join("\n") : "";
}

function sidecarValue(workbench) {
  const templateOrigin = normalizedTemplateOrigin(workbench);
  return {
    version: workbench.version || 1,
    ...(workbench.projectName ? { projectName: workbench.projectName } : {}),
    name: workbench.name,
    profile: workbench.profile,
    session: workbench.session,
    permission: workbench.permission,
    watchdog: workbench.watchdog,
    rebuild: workbench.rebuild,
    ...(templateOrigin ? { templateOrigin } : {}),
    roles: (workbench.roles || []).map((role) => ({
      id: role.id,
      name: role.name,
      type: role.type,
      description: role.description,
    })),
  };
}

function normalizedTemplateOrigin(workbench) {
  const explicit = workbench?.templateOrigin;
  if (explicit && PROJECT_PATTERN.test(explicit.id || "")) {
    return { id: explicit.id, version: Number.isInteger(explicit.version) ? explicit.version : "unknown" };
  }
  const inferred = typeof workbench?.profile === "string" ? workbench.profile.match(/^user:([A-Za-z0-9][A-Za-z0-9._-]*)$/) : null;
  return inferred ? { id: inferred[1], version: "unknown" } : null;
}

export function serializeWorkbenchSidecar(workbench) {
  return `${JSON.stringify(sidecarValue(workbench), null, 2)}\n`;
}

function assertStagedRoundTrip(workbench, stagingDirectory) {
  for (const role of workbench.roles) {
    if (!ROLE_PATTERN.test(role.id || "")) throw new Error(`角色 ID 无法写入：${role.id || "<empty>"}`);
    if (CONTROL_PATTERN.test(role.agent || "") || /^(claude|codex|kimi|shell):\s*$/.test(role.agent || "")) {
      throw new Error(`角色 ${role.id} 的 Agent 无法安全写入`);
    }
    if (CONTROL_PATTERN.test(role.model || "")) throw new Error(`角色 ${role.id} 的模型无法安全写入`);
  }
  const agentRows = parseRoleMap(readText(path.join(stagingDirectory, "agents.conf")));
  if (agentRows.some((row) => !row.value)) throw new Error("agents.conf 的 Agent 值不能为空");
  if (new Set(agentRows.map((row) => row.id)).size !== agentRows.length) throw new Error("agents.conf 包含重复角色 ID");
  if (agentRows.length !== workbench.roles.length || agentRows.some((row, index) => (
    row.id !== workbench.roles[index].id || row.value !== workbench.roles[index].agent.trim()
  ))) throw new Error("agents.conf round-trip 自检失败");
  if (!agentRows.some((row) => row.id === "hub")) throw new Error("agents.conf 缺少 hub");

  const modelsFile = path.join(stagingDirectory, "models.conf");
  const modelRows = existsSync(modelsFile) ? parseRoleMap(readText(modelsFile)) : [];
  const expectedModels = workbench.roles.filter((role) => typeof role.model === "string" && role.model.trim());
  if (modelRows.length !== expectedModels.length || modelRows.some((row, index) => (
    row.id !== expectedModels[index].id || row.value !== expectedModels[index].model.trim()
  ))) throw new Error("models.conf round-trip 自检失败");

  for (const role of workbench.roles) {
    const promptName = role.id === "hub" ? "hub-extension.md" : `${role.id}.md`;
    if (!existsSync(path.join(stagingDirectory, "prompts", promptName))) throw new Error(`缺少 prompt：${promptName}`);
    if (role.id !== "hub" && !readText(path.join(stagingDirectory, "prompts", promptName)).trim()) {
      throw new Error(`角色 ${role.id} 的 prompt 不能为空`);
    }
  }
  const sidecar = JSON.parse(readText(path.join(stagingDirectory, "workbench.json")));
  if ((sidecar.roles || []).some((role) => "agent" in role || "model" in role || "prompt" in role)) {
    throw new Error("workbench.json 包含权威配置字段");
  }
}

function sidecarFields(workspace, projectName, value) {
  if (!value) return null;
  const saved = { workspace, projectName };
  for (const key of ["version", "name", "profile", "session", "permission", "watchdog", "rebuild"]) {
    if (value[key] !== undefined) saved[key] = value[key];
  }
  const templateOrigin = normalizedTemplateOrigin(value);
  if (templateOrigin) saved.templateOrigin = templateOrigin;
  saved.roles = Array.isArray(value.roles) ? value.roles.flatMap((role) => (
    role && typeof role === "object" && typeof role.id === "string"
      ? [{ id: role.id, name: role.name, type: role.type, description: role.description }]
      : []
  )) : [];
  return saved;
}

function readModelMap(directory) {
  const file = path.join(directory, "models.conf");
  if (!existsSync(file)) return new Map();
  return new Map(parseRoleMap(readText(file)).map(({ id, value }) => [id, value]));
}

function stageProjectState(workbench, stagingDirectory) {
  const stagingPrompts = path.join(stagingDirectory, "prompts");
  mkdirSync(stagingPrompts, { recursive: true });
  writeFileSync(path.join(stagingDirectory, "agents.conf"), serializeAgents(workbench), { mode: 0o600 });
  const models = serializeModels(workbench);
  if (models) writeFileSync(path.join(stagingDirectory, "models.conf"), models, { mode: 0o600 });
  for (const role of workbench.roles) {
    const promptName = role.id === "hub" ? "hub-extension.md" : `${role.id}.md`;
    writeFileSync(path.join(stagingPrompts, promptName), `${composeRolePrompt(role).trim()}\n`, { mode: 0o600 });
  }
  writeFileSync(path.join(stagingDirectory, "workbench.json"), serializeWorkbenchSidecar(workbench), { mode: 0o600 });

  try {
    assertStagedRoundTrip(workbench, stagingDirectory);
  } catch (error) {
    rmSync(stagingDirectory, { recursive: true, force: true });
    throw new Error(`配置预校验失败：${error.message}`);
  }
}

function commitStagedState(workbench, stagingDirectory, targetDirectory) {
  const stagingPrompts = path.join(stagingDirectory, "prompts");
  mkdirSync(targetDirectory, { recursive: true });
  const promptDirectory = path.join(targetDirectory, "prompts");
  mkdirSync(promptDirectory, { recursive: true });
  try {
    renameSync(path.join(stagingDirectory, "agents.conf"), path.join(targetDirectory, "agents.conf"));
    const stagedModels = path.join(stagingDirectory, "models.conf");
    const modelsFile = path.join(targetDirectory, "models.conf");
    if (existsSync(stagedModels)) renameSync(stagedModels, modelsFile);
    else if (existsSync(modelsFile)) unlinkSync(modelsFile);
    for (const role of workbench.roles) {
      const promptName = role.id === "hub" ? "hub-extension.md" : `${role.id}.md`;
      renameSync(path.join(stagingPrompts, promptName), path.join(promptDirectory, promptName));
    }
    const currentPromptFiles = new Set(workbench.roles.map((role) => role.id === "hub" ? "hub-extension.md" : `${role.id}.md`));
    for (const entry of readdirSync(promptDirectory, { withFileTypes: true })) {
      const role = entry.name.endsWith(".md") ? entry.name.slice(0, -3) : "";
      if (entry.isFile() && ROLE_PATTERN.test(role) && !currentPromptFiles.has(entry.name)) {
        unlinkSync(path.join(promptDirectory, entry.name));
      }
    }
    // The UI sidecar is the commit marker and is intentionally renamed last.
    renameSync(path.join(stagingDirectory, "workbench.json"), path.join(targetDirectory, "workbench.json"));
    rmSync(stagingDirectory, { recursive: true, force: true });
  } catch (error) {
    error.message = `配置提交失败；staging 副本保留在 ${stagingDirectory}：${error.message}`;
    error.stagingDirectory = stagingDirectory;
    throw error;
  }
}

function migrateLegacyAndSave(workbench, legacy, { renameImpl = renameSync } = {}) {
  const projectsRoot = path.join(localRoot(workbench.workspace), "projects");
  const legacyTarget = projectDir(workbench.workspace, legacy.name);
  const newTarget = projectDir(workbench.workspace, workbench.projectName);
  if (existsSync(legacyTarget) || existsSync(newTarget)) throw new Error("项目目录已存在，无法执行惰性迁移");
  mkdirSync(projectsRoot, { recursive: true });
  const nonce = `${process.pid}-${randomBytes(4).toString("hex")}`;
  const legacyStage = path.join(projectsRoot, `.staging-migrate-${nonce}`);
  const newStage = path.join(projectsRoot, `.staging-new-${nonce}`);
  stageProjectState(workbench, newStage);
  mkdirSync(legacyStage);
  let legacyLocation = legacyStage;
  try {
    for (const name of PROJECT_FILES) {
      const source = path.join(legacy.directory, name);
      if (existsSync(source)) renameImpl(source, path.join(legacyStage, name));
    }
    renameImpl(legacyStage, legacyTarget);
    legacyLocation = legacyTarget;
    renameImpl(newStage, newTarget);
  } catch (error) {
    for (const name of PROJECT_FILES) {
      const source = path.join(legacyLocation, name);
      if (existsSync(source)) renameSync(source, path.join(legacy.directory, name));
    }
    rmSync(legacyStage, { recursive: true, force: true });
    rmSync(legacyTarget, { recursive: true, force: true });
    rmSync(newStage, { recursive: true, force: true });
    rmSync(newTarget, { recursive: true, force: true });
    throw new Error(`项目迁移失败，旧配置已回滚：${error.message}`);
  }
}

export function saveProjectState(workbench, options = {}) {
  const root = localRoot(workbench.workspace);
  const projectName = workbench.projectName || "";
  if (projectName && !PROJECT_PATTERN.test(projectName)) throw new Error("项目名只能包含字母、数字、点、下划线和连字符");
  const stored = listStoredProjects(workbench.workspace);
  const legacy = stored.length === 1 && stored[0].legacy ? stored[0] : null;
  if (projectName && legacy && legacy.name !== projectName) {
    migrateLegacyAndSave(workbench, legacy, options);
    return;
  }
  const existing = projectName ? stored.find((project) => project.name === projectName) : null;
  const targetDirectory = projectName
    ? existing?.directory || projectDir(workbench.workspace, projectName)
    : root;
  mkdirSync(path.dirname(targetDirectory), { recursive: true });
  const stagingDirectory = path.join(path.dirname(targetDirectory), `.staging-${process.pid}-${randomBytes(4).toString("hex")}`);
  stageProjectState(workbench, stagingDirectory);
  commitStagedState(workbench, stagingDirectory, targetDirectory);
}

export function loadProjectState(workspace, name, options) {
  const {
    profiles,
    prompts,
    roleMeta,
    defaultWorkbench,
    promptForRole,
    normalizeWorkbench,
    validateWorkbench,
  } = options;
  const stored = listStoredProjects(workspace);
  if (!name && stored.length > 1) throw new Error("该目录包含多个项目，请指定项目名");
  const selected = stored.find((project) => project.name === name)
    || (!name ? stored[0] : null)
    || { name: name || legacyProjectName(workspace, null), directory: name ? projectDir(workspace, name) : localRoot(workspace), legacy: !name };
  const projectName = selected.name;
  const directory = selected.directory;
  let raw = rawSidecar(directory);
  const agentsFile = path.join(directory, "agents.conf");
  if (!existsSync(agentsFile) && Array.isArray(raw?.roles) && raw.roles.length) {
    const legacy = normalizeWorkbench({ ...raw, workspace, projectName });
    if (validateWorkbench(legacy).valid) {
      saveProjectState(legacy);
      raw = rawSidecar(directory);
    }
  }

  const saved = sidecarFields(workspace, projectName, raw);
  const selectedProfile = profiles.find((profile) => profile.id === saved?.profile)
    || profiles.find((profile) => profile.id === "config1")
    || profiles[0];
  const fallback = defaultWorkbench(workspace, projectName, directory, selectedProfile, prompts);
  if (!existsSync(agentsFile)) {
    const { roles: _savedRoles, ...savedFields } = saved || {};
    return normalizeWorkbench({ ...fallback, ...savedFields, workspace, projectName });
  }

  const models = readModelMap(directory);
  const savedRoles = new Map((saved?.roles || []).map((role) => [role.id, role]));
  const roles = parseRoleMap(readText(agentsFile)).map(({ id, value: agent }) => {
    const known = roleMeta[id];
    const metadata = savedRoles.get(id) || {};
    const prompt = promptForRole(directory, id, prompts);
    return {
      id,
      name: known?.name || metadata.name || id,
      type: known?.type || metadata.type || "specialist",
      description: known?.description || metadata.description || "自定义协作角色",
      agent,
      model: models.get(id) || "",
      promptTemplate: prompt.template,
      prompt: prompt.body,
      promptBase: prompt.promptBase,
      intent: prompt.intent,
      promptMode: prompt.promptMode,
    };
  });
  const { roles: _savedRoles, ...savedFields } = saved || {};
  return normalizeWorkbench({ ...fallback, ...savedFields, workspace, projectName, roles });
}
